-- AlterTable
ALTER TABLE "Club" DROP COLUMN "maxCapacity";
ALTER TABLE "Club" ADD COLUMN "grade1Capacity" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Club" ADD COLUMN "grade2Capacity" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Club" ADD COLUMN "grade3Capacity" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Club" ADD COLUMN "openAt" TIMESTAMP(3);
